In [76]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# sklearn 모델의 동일한 결과 출력을 위해 선언합니다.
import numpy as np
import pandas as pd
np.random.seed(5)

In [77]:
district_dict_list = [
            {'district': 'Gangseo-gu', 'latitude': 37.551000, 'longitude': 126.849500, 'label':'Gangseo'},
            {'district': 'Yangcheon-gu', 'latitude': 37.52424, 'longitude': 126.855396, 'label':'Gangseo'},
            {'district': 'Guro-gu', 'latitude': 37.4954, 'longitude': 126.8874, 'label':'Gangseo'},
            {'district': 'Geumcheon-gu', 'latitude': 37.4519, 'longitude': 126.9020, 'label':'Gangseo'},
            {'district': 'Mapo-gu', 'latitude': 37.560229, 'longitude': 126.908728, 'label':'Gangseo'},
            
            {'district': 'Gwanak-gu', 'latitude': 37.487517, 'longitude': 126.915065, 'label':'Gangnam'},
            {'district': 'Dongjak-gu', 'latitude': 37.5124, 'longitude': 126.9393, 'label':'Gangnam'},
            {'district': 'Seocho-gu', 'latitude': 37.4837, 'longitude': 127.0324, 'label':'Gangnam'},
            {'district': 'Gangnam-gu', 'latitude': 37.5172, 'longitude': 127.0473, 'label':'Gangnam'},
            {'district': 'Songpa-gu', 'latitude': 37.503510, 'longitude': 127.117898, 'label':'Gangnam'},
   
            {'district': 'Yongsan-gu', 'latitude': 37.532561, 'longitude': 127.008605, 'label':'Gangbuk'},
            {'district': 'Jongro-gu', 'latitude': 37.5730, 'longitude': 126.9794, 'label':'Gangbuk'},
            {'district': 'Seongbuk-gu', 'latitude': 37.603979, 'longitude': 127.056344, 'label':'Gangbuk'},
            {'district': 'Nowon-gu', 'latitude': 37.6542, 'longitude': 127.0568, 'label':'Gangbuk'},
            {'district': 'Dobong-gu', 'latitude': 37.6688, 'longitude': 127.0471, 'label':'Gangbuk'},
     
            {'district': 'Seongdong-gu', 'latitude': 37.557340, 'longitude': 127.041667, 'label':'Gangdong'},
            {'district': 'Dongdaemun-gu', 'latitude': 37.575759, 'longitude': 127.025288, 'label':'Gangdong'},
            {'district': 'Gwangjin-gu', 'latitude': 37.557562, 'longitude': 127.083467, 'label':'Gangdong'},
            {'district': 'Gangdong-gu', 'latitude': 37.554194, 'longitude': 127.151405, 'label':'Gangdong'},
            {'district': 'Jungrang-gu', 'latitude': 37.593684, 'longitude': 127.090384, 'label':'Gangdong'}
         ]

train_df = pd.DataFrame(district_dict_list)
train_df = train_df[['district', 'longitude', 'latitude', 'label']]

In [78]:
train_df

district   longitude   latitude     label
0      Gangseo-gu  126.849500  37.551000   Gangseo
1    Yangcheon-gu  126.855396  37.524240   Gangseo
2         Guro-gu  126.887400  37.495400   Gangseo
3    Geumcheon-gu  126.902000  37.451900   Gangseo
4         Mapo-gu  126.908728  37.560229   Gangseo
5       Gwanak-gu  126.915065  37.487517   Gangnam
6      Dongjak-gu  126.939300  37.512400   Gangnam
7       Seocho-gu  127.032400  37.483700   Gangnam
8      Gangnam-gu  127.047300  37.517200   Gangnam
9       Songpa-gu  127.117898  37.503510   Gangnam
10     Yongsan-gu  127.008605  37.532561   Gangbuk
11      Jongro-gu  126.979400  37.573000   Gangbuk
12    Seongbuk-gu  127.056344  37.603979   Gangbuk
13       Nowon-gu  127.056800  37.654200   Gangbuk
14      Dobong-gu  127.047100  37.668800   Gangbuk
15   Seongdong-gu  127.041667  37.557340  Gangdong
16  Dongdaemun-gu  127.025288  37.575759  Gangdong
17    Gwangjin-gu  127.083467  37.557562  Gangdong
18    Gangdong-gu  127.151405  37.554194  Gangdong
19    Jungrang-gu  127.090384  37.593684  Gangdong

In [79]:
dong_dict_list = [
            {'dong': 'Gaebong-dong', 'latitude': 37.489853, 'longitude': 126.854547, 'label':'Gangseo'},
            {'dong': 'Gochuk-dong', 'latitude': 37.501394, 'longitude': 126.859245, 'label':'Gangseo'},
            {'dong': 'Hwagok-dong', 'latitude': 37.537759, 'longitude': 126.847951, 'label':'Gangseo'},
            {'dong': 'Banghwa-dong', 'latitude': 37.575817, 'longitude': 126.815719, 'label':'Gangseo'},
            {'dong': 'Sangam-dong', 'latitude': 37.577039, 'longitude': 126.891620, 'label':'Gangseo'},
            
            {'dong': 'Nonhyun-dong', 'latitude': 37.508838, 'longitude': 127.030720, 'label':'Gangnam'},
            {'dong': 'Daechi-dong', 'latitude': 37.501163, 'longitude': 127.057193, 'label':'Gangnam'},
            {'dong': 'Seocho-dong', 'latitude': 37.486401, 'longitude': 127.018281, 'label':'Gangnam'},
            {'dong': 'Bangbae-dong', 'latitude': 37.483279, 'longitude': 126.988194, 'label':'Gangnam'},
            {'dong': 'Dogok-dong', 'latitude': 37.492896, 'longitude': 127.043159, 'label':'Gangnam'},
    
            {'dong': 'Pyoungchang-dong', 'latitude': 37.612129, 'longitude': 126.975724, 'label':'Gangbuk'},
            {'dong': 'Sungbuk-dong', 'latitude': 37.597916, 'longitude': 126.998067, 'label':'Gangbuk'},
            {'dong': 'Ssangmoon-dong', 'latitude': 37.648094, 'longitude': 127.030421, 'label':'Gangbuk'},
            {'dong': 'Ui-dong', 'latitude': 37.648446, 'longitude': 127.011396, 'label':'Gangbuk'},
            {'dong': 'Samcheong-dong', 'latitude': 37.591109, 'longitude': 126.980488, 'label':'Gangbuk'},
    
            {'dong': 'Hwayang-dong', 'latitude': 37.544234, 'longitude': 127.071648, 'label':'Gangdong'},
            {'dong': 'Gui-dong', 'latitude': 37.543757, 'longitude': 127.086803, 'label':'Gangdong'},
            {'dong': 'Neung-dong', 'latitude': 37.553102, 'longitude': 127.080248, 'label':'Gangdong'},
            {'dong': 'Amsa-dong', 'latitude': 37.552370, 'longitude': 127.127124, 'label':'Gangdong'},
            {'dong': 'Chunho-dong', 'latitude': 37.547436, 'longitude': 127.137382, 'label':'Gangdong'}
         ]

test_df = pd.DataFrame(dong_dict_list)
test_df = test_df[['dong', 'longitude', 'latitude', 'label']]

In [80]:
test_df

dong   longitude   latitude     label
0       Gaebong-dong  126.854547  37.489853   Gangseo
1        Gochuk-dong  126.859245  37.501394   Gangseo
2        Hwagok-dong  126.847951  37.537759   Gangseo
3       Banghwa-dong  126.815719  37.575817   Gangseo
4        Sangam-dong  126.891620  37.577039   Gangseo
5       Nonhyun-dong  127.030720  37.508838   Gangnam
6        Daechi-dong  127.057193  37.501163   Gangnam
7        Seocho-dong  127.018281  37.486401   Gangnam
8       Bangbae-dong  126.988194  37.483279   Gangnam
9         Dogok-dong  127.043159  37.492896   Gangnam
10  Pyoungchang-dong  126.975724  37.612129   Gangbuk
11      Sungbuk-dong  126.998067  37.597916   Gangbuk
12    Ssangmoon-dong  127.030421  37.648094   Gangbuk
13           Ui-dong  127.011396  37.648446   Gangbuk
14    Samcheong-dong  126.980488  37.591109   Gangbuk
15      Hwayang-dong  127.071648  37.544234  Gangdong
16          Gui-dong  127.086803  37.543757  Gangdong
17        Neung-dong  127.080248  37.553102  Gangdong
18         Amsa-dong  127.127124  37.552370  Gangdong
19       Chunho-dong  127.137382  37.547436  Gangdong

In [81]:
##하드보팅 소프트보팅 하기.
train_df.drop(['district'], axis = 1, inplace = True)
test_df.drop(['dong'], axis = 1, inplace = True)

In [82]:
dtree = DecisionTreeClassifier(
    criterion = 'entropy', #gini vs entropy  entropy는 매우 높을때 정보량도 많다. 
    max_depth = 25, 
    random_state = 35
)

In [83]:
knn = KNeighborsClassifier(
    n_neighbors = 10, 
    n_jobs = None
)

In [84]:
svm = SVC(
    C = 0.1, 
    gamma = 0.003, 
    kernel = 'rbf',
    probability = True #값 라벨링값으로 될 가능성 
)

In [85]:
dtree.fit(train_df[['longitude', 'latitude']], train_df['label'])
dtree_predicted = dtree.predict(test_df[['longitude', 'latitude']])
accuracy_score(test_df['label'], dtree_predicted)

0.95

In [86]:
knn.fit(train_df[['longitude', 'latitude']], train_df['label'])
knn_predicted = knn.predict(test_df[['longitude', 'latitude']])
accuracy_score(test_df['label'], knn_predicted)

0.9

In [87]:
svm.fit(train_df[['longitude', 'latitude']], train_df['label'])
svm_predicted = svm.predict(test_df[['longitude', 'latitude']])
accuracy_score(test_df['label'], svm_predicted)

0.95

In [88]:
dtree_proba = dtree.predict_proba(test_df[['longitude','latitude']])
print(dtree_proba[:8])

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [89]:
knn_proba = knn.predict_proba(test_df[['longitude', 'latitude']])
print(knn_proba[:8])

[[0.2 0.  0.3 0.5]
 [0.2 0.  0.3 0.5]
 [0.2 0.1 0.2 0.5]
 [0.2 0.1 0.2 0.5]
 [0.2 0.1 0.2 0.5]
 [0.3 0.3 0.4 0. ]
 [0.3 0.4 0.3 0. ]
 [0.2 0.3 0.5 0. ]]


In [90]:
svm_proba = svm.predict_proba(test_df[['longitude', 'latitude']])
print(svm_proba[:8])

[[0.03004092 0.01704318 0.13921812 0.81369778]
 [0.03870726 0.01964391 0.14674788 0.79490096]
 [0.05575531 0.01906605 0.11375979 0.81141886]
 [0.05607002 0.01258089 0.06100382 0.87034527]
 [0.19515759 0.04584079 0.1823224  0.57667923]
 [0.16043169 0.25119803 0.49411095 0.09425932]
 [0.12917146 0.33431645 0.47496738 0.06154471]
 [0.10888426 0.18189176 0.58866315 0.12056083]]


In [91]:
np.argmax(dtree_proba)

3

In [92]:
np.argmax(knn_proba)

3

In [93]:
np.argmax(svm_proba)

15

In [94]:
voting_clf1 = VotingClassifier(
    estimators=[
        ('decision tree', dtree), 
        ('knn', knn), 
        ('svm', svm)
    ], 
    weights = [1,1,1], 
    voting = 'hard'

)

In [95]:
voting_clf1.fit(train_df[['longitude', 'latitude']], train_df[['label']])
hard_voting_predicted = voting_clf1.predict(test_df[['longitude', 'latitude']])
accuracy_score(test_df[['label']], hard_voting_predicted)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.95

In [96]:
voting_clf2 = VotingClassifier(
    estimators=[
        ('decision tree', dtree), 
        ('knn', knn), 
        ('svm', svm)
    ], 
    weights = [1,1,1], 
    voting = 'soft'

)

In [97]:
voting_clf2.fit(train_df[['longitude','latitude']], train_df[['label']]) 
soft_voting_predicted = voting_clf2.predict(test_df[['longitude', 'latitude']])
accuracy_score(test_df[['label']], soft_voting_predicted)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.95

In [100]:
train_3_df = pd.DataFrame({
        "longitude":[127.057193,127.057123,127.059234],
        "latitude":[37.591109,37.594244,37.596556],
        "label":['Gangbuk','Gangnam','Gangseo']
})

train_3_df

longitude   latitude    label
0  127.057193  37.591109  Gangbuk
1  127.057123  37.594244  Gangnam
2  127.059234  37.596556  Gangseo

In [101]:
test_3_df = pd.DataFrame({
        "longitude":[127.057193,127.057123,127.059234],
        "latitude":[37.591109,37.594244,37.596556],
        "label":['Gangbuk','Gangnam','Gangseo']
})

test_3_df

longitude   latitude    label
0  127.057193  37.591109  Gangbuk
1  127.057123  37.594244  Gangnam
2  127.059234  37.596556  Gangseo

In [102]:
#voting_clf1.fit(test_3_df[['longitude', 'latitude']], test_3_df[['label']])

hard_voting_predicted = voting_clf1.predict(train_3_df[['longitude', 'latitude']])
accuracy_score(test_3_df[['label']], hard_voting_predicted)

0.3333333333333333

In [103]:
soft_voting_predicted = voting_clf2.predict(train_3_df[['longitude', 'latitude']])
accuracy_score(test_3_df[['label']], soft_voting_predicted)

0.3333333333333333

In [106]:
dtree_proba = knn.predict_proba(test_3_df[['longitude', 'latitude']])
dtree_proba

array([[0.5, 0.4, 0.1, 0. ],
       [0.5, 0.4, 0.1, 0. ],
       [0.5, 0.4, 0.1, 0. ]])

In [107]:
knn_proba = knn.predict_proba(test_3_df[['longitude', 'latitude']])
knn_proba


array([[0.5, 0.4, 0.1, 0. ],
       [0.5, 0.4, 0.1, 0. ],
       [0.5, 0.4, 0.1, 0. ]])

In [108]:
svm_proba = svm.predict_proba(test_3_df[['longitude', 'latitude']])
svm_proba

array([[0.4590438 , 0.35383433, 0.14570604, 0.04141582],
       [0.473821  , 0.34766983, 0.13807872, 0.04043045],
       [0.47913444, 0.35228029, 0.13032648, 0.03825878]])